project:
  type: website

website:
  search: false
  title: "Konrad Swierczek"
  favicon: assets/favicon.png
  navbar:
    background: primary
    right:
      - sound.qmd
      - music.qmd
      - research.qmd
      - contact.qmd
  page-footer:
    right: 
      - icon: envelope
        href: mailto:konrad@konradswierczek.ca
      - icon: github
        href: https://github.com/konradswierczek/

format:
  html:
    theme: cosmo
    css: styles.css
